# -*- coding: utf-8 -*-
from click.core import Command as Command, Context, Group, Option, Parameter as Parameter
from click.formatting import HelpFormatter as HelpFormatter
from typing import Any, Iterable, Mapping

COL_MAX: int
MAX_CONTENT_WIDTH: int
TERMINAL_WIDTH: int
SEPARATOR: str


def up(value: str): ...


def underscore_to_dash(value: str, *, prefix: bool = True): ...


def wrap_line(line: str): ...


def add_brackets(value: str): ...


def format_usage(cmd: Command, ctx: Context, formatter: HelpFormatter) -> None: ...


def format_options(cmd: Command, ctx: Context, formatter: HelpFormatter) -> None: ...


def format_epilog(cmd: Command, parent: Context = None, formatter: HelpFormatter = None) -> None: ...


def format_help(cmd: Command, ctx: Context, formatter: HelpFormatter) -> None: ...


def format_args(cmd: Command, ctx: Context, formatter: HelpFormatter): ...


def get_help(cmd: Command, ctx: Context) -> str: ...


def recursive_help(cmd: Command, parent: Context = None, lines: Iterable[str] = None): ...


def print_version(ctx: Context, param: Parameter, value: Any): ...


class APIGroup(Group):
    def __init__(self, **attrs: Any) -> None: ...

    def format_help(self, ctx: Context, formatter: HelpFormatter) -> None: ...

    def format_usage(self, ctx: Context, formatter: HelpFormatter) -> None: ...

    def get_usage(self, ctx: Context) -> str: ...

    def format_options(self, ctx: Context, formatter: HelpFormatter) -> None: ...

    def format_epilog(self, ctx: Context, formatter: HelpFormatter) -> None: ...

    def format_args(self, ctx: Context, formatter: HelpFormatter): ...

    def parse_args(self, ctx: Context, args: list[str]) -> list[str]: ...

    def invoke(self, ctx: Context) -> Any: ...


class SwitchArgsAPIGroup(APIGroup):
    def parse_args(self, ctx: Context, args: list[str]): ...


class TermsAPIGroup(APIGroup):
    def parse_args(self, ctx: Context, args: list[str]): ...


class MutuallyExclusiveOption(Option):
    mutually_exclusive: set[str]

    def __init__(self, *args, **kwargs) -> None: ...

    def handle_parse_result(self, ctx: Context, opts: Mapping[str, Any], args: Iterable[str]) -> tuple[
        Any, list[str]]: ...


def cli(debug: bool = False): ...


def clear_logs(ctx: Context): ...
