# -*- coding: utf-8 -*-
from utilities.common.shared import MAX_SYMBOLS as MAX_SYMBOLS, MIN_COLUMN as MIN_COLUMN
from utilities.table_cols.column import TableColumnParameters as TableColumnParameters


class TableAnalyser:
    def __init__(self, *, max_symbols: int = None, min_column: int = None) -> None: ...

    def nullify(self) -> None: ...

    def __iter__(self): ...

    def inspect_valid(self) -> None: ...

    def find_base_column_width(self, column_parameters: TableColumnParameters): ...

    def set_base_column_widths(self) -> None: ...

    def distribute_rest(self) -> None: ...

    @property
    def percentages(self): ...

    def __bool__(self) -> bool: ...
