# -*- coding: utf-8 -*-
from utilities.set_table_cols.coordinate import TableCoordinate


def fix_length(text: str): ...


class TableCell:
    def __init__(
            self,
            table_coordinate: TableCoordinate,
            text: str = None,
            row_modifier: int = 1,
            column_modifier: int = 1) -> None: ...

    def __hash__(self): ...

    @property
    def raw_text(self): ...

    def processed_text(self): ...

    @property
    def occupied_elements(self) -> int: ...

    def __bool__(self) -> bool: ...

    def is_spaced(self) -> bool: ...

    @property
    def coord(self) -> tuple[int, int]: ...

    def __eq__(self, other): ...

    def __ne__(self, other): ...

    @property
    def minimum_length(self) -> int: ...

    @property
    def preferred_length(self) -> int: ...

    def __len__(self) -> int: ...

    @property
    def text(self): ...
