# -*- coding: utf-8 -*-
from pathlib import Path
from typing import Iterable, Iterator
from utilities.common.errors import TableColsTableBorderNotClosedError as TableColsTableBorderNotClosedError
from utilities.common.functions import file_writer as file_writer
from utilities.table_cols import TableAnalyser as TableAnalyser
from utilities.table_cols.column import TableColumn as TableColumn
from utilities.table_cols.table import Table as Table


class AsciiDocFile:
    def __init__(self, path: str | Path, *, content: Iterable[str] = None) -> None: ...

    def __iter__(self): ...

    def __len__(self) -> int: ...

    def __getitem__(self, item): ...

    def __setitem__(self, key, value) -> None: ...

    def table_borders(self) -> Iterator[tuple[int, int]]: ...

    def set_tables(self) -> None: ...

    def replace_tables(self) -> None: ...

    def fix_tables(self, table_analyser: TableAnalyser): ...

    def save(self) -> None: ...
