# -*- coding: utf-8 -*-
from pathlib import Path
from typing import Iterable, Iterator, Mapping

from utilities.table_cols.analyser import TableAnalyser


class AsciiDocFile:
    def __init__(self, path: str | Path, *, content: Iterable[str] = None) -> None: ...

    def __iter__(self): ...

    def __len__(self) -> int: ...

    def __getitem__(self, item): ...

    def __setitem__(self, key, value) -> None: ...

    def table_borders(self) -> Iterator[tuple[int, int]]: ...

    def set_tables(self) -> None: ...

    def replace_tables(self) -> None: ...

    def fix_tables(self, table_analyser: TableAnalyser, options: Mapping[str, str] = None): ...

    def save(self) -> None: ...
