# -*- coding: utf-8 -*-
from typing import Iterable, Iterator, Mapping

from utilities.set_table_cols.column import TableColumn


class Table:
    def __init__(
            self,
            name: str | None = None,
            index: int | None = None,
            lines: Iterable[str] = None,
            options: Mapping[str, str | None] = None) -> None: ...

    def has_horizontal_span(self): ...

    def __iter__(self) -> Iterator[str]: ...

    def __eq__(self, other): ...

    def __ne__(self, other): ...

    def __hash__(self): ...

    def __getitem__(self, item): ...

    def nullify(self) -> None: ...

    def content(self) -> str: ...

    def define_cells(self) -> None: ...

    def options_str(self) -> str: ...

    def __len__(self) -> int: ...

    @property
    def num_columns(self) -> int: ...

    def get_column_item(self, column: int | str) -> TableColumn: ...

    def iter_column_items(self) -> Iterator['TableColumn']: ...

    def __bool__(self) -> bool: ...

    @property
    def table_cells(self): ...

    @property
    def options(self): ...

    @property
    def index(self): ...

    @property
    def name(self): ...

    @property
    def column_names(self) -> list[str]: ...
