[tool.poetry]
name = "utilities"
version = "1.0.0"
description = "Command line interface commands for technical writers"
authors = ["Andrew Tarasov <tarasov-a@protei.ru>"]
license = "MIT"
readme = "README.adoc"

[tool.poetry.dependencies]
python = ">=3.9"
loguru = ">=0.6"
click = ">=8.1"
more-itertools = ">=10.5"
pyyaml = ">6.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3"
flake8 = ">=7.1"
vulture = ">=2.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
my-script = "__main__.py"
