path_note: &path_note >-
  NOTE: Путь может быть как абсолютным, так и относительным.

attributes: |
  :imagesdir: images
  :stylesdir: ../css
  :stylesheet: default.css
  :toc-title: Содержание
  :pdf-themesdir: themes
  :pdf-theme: base-theme.yml
  :asciidoctorconfigdir: ../
  :experimental:
  :icons: font
  :table-caption: Таблица
  :colon: :

check-russian:
  description: |
    Скрипт проверяет наличие кириллических символов в файлах. +
    В результате отображается информация, найдены ли не латинские символы:
    +
    [,log]
    ----
    В файле <path to file> <найдены/не найдены> кириллические буквы [в строках: <line no>, ..., <line no>]
    ----
    +
    * `path to file` -- путь до файла;
    * `line no` -- номер строки в файле, где найдены кириллические символы.
    
    Поскольку в выводе возможно много строк, то для удобства ориентирования в нем используется интуитивная цветовая индикация.
    +
    CAUTION: Скрипт не показывает непереведенные слова или подмены схожих букв, это остается делом пользователя, а указывает лишь на файлы, строки и символы.
  purpose: При переводе вручную можно вполне себе забыть или не заметить какие-то фразы/слова/предложения, оставшиеся на русском языке.
  admonitions:
    - "NOTE: При указании директории в ней выбираются файлы, в которых присутствует постфикс `.en`."
    - *path_note
  others:

convert-tables:
  description: |
    Скрипт извлекает из файла Word формата *.docx или *.docm все таблицы и преобразует их в формат Markdown.
    Каждая таблица записывается в отдельный файл под тем же номером, что и в исходном файле.
  purpose: |
    При использовании `pandoc`, самого распространенного программного обеспечения для конвертации файлов, таблицы в некоторых случаях обрабатываются некорректно.
    Например, если заголовок многоуровневый; содержит текст, расположенный на нескольких строках и др. возможные случаи.
  admonitions:
    - *path_note
  others:

filter-images:
  description: Скрипт проверяет все ссылки в текстовых файлах и ищет изображения, которые не упомянуты ни разу.
  purpose: |
    Часто схемы, диаграммы, скриншоты со временем меняются, но старые версии оставляются про запас или для случаев, если они потенциально могут быть полезны. +
    Тогда проекты могут содержать множество неиспользуемых файлов, которые:
    +
    * Занимают дисковое пространство;
    * Усложняют структуру проекта;
    * Увеличивают шансы добавить ссылки на некорректные изображения.
  admonitions:
    - *path_note
  others:

format-code:
  description: |
    Скрипт форматирует блоки кода, разбивая их на строки, которые может в себя вместить PDF-файл без непреднамеренного переноса. +
    Разбиение осуществляется по отдельным словам, добавляя разрыв строки:
    +
    * после 'точки с запятой';
    * перед 'открывающей скобкой';
    * после 'запятой'.
  purpose: |
    Записи журналов или примеры сущностей API могут иметь крайне длинные строки, которые превышают допустимую в PDF.
    В таком случае разрыв добавляется в "случайное" место в слове, чтобы все буквы уместились.
    Место, разумеется, выбирается не случайным образом, однако в любом случае повлиять на него со стороны невозможно.
  admonitions:
    - *path_note
  others:

generate-yaml:
  description: |
    Скрипт генерирует файл `PDF_*.yml` для создания PDF. +
    В результате записывается файл `PDF_<title-page>.yml` для русского языка и `PDF_<title-page>.<language>.yml` для иностранного языка, который следует структуре проекта. +
    При этом учитывается вес файлов и не включаются черновые файлы.
    +
    CAUTION: Файл записывается в директорию указанного проекта.
  purpose: |
    В проекте может быть большое количество файлов в разных статусах.
    Проекты могут иметь большой уровень вложенности.
    Не всегда удается вручную отсеять нужное для заполнения `PDF_*.yml`.
  admonitions:
    - *path_note
    - "WARNING: Файлы, чье имя начинается с `.` или `_` игнорируются, поскольку это, как правило, временные или служебные файлы, к тому же игнорируемые всеми генераторами статических сайтов."
  others:

get-terms:
  description: Скрипт выводит расшифровки аббревиатур и сокращений, используемых в документации продуктов сетевых и мобильных технологий.
  purpose: |
    При создании или изменении документа часто встречаются широко используемые аббревиатуры, которые не всегда с первого взгляда ясны и понятны.
    Также необходимо добавлять пояснения к сокращениям по тексту, поскольку достаточно многие имеют несколько возможных вариантов интерпретации.
  admonitions:
  others:

help:
  description: Скрипт выводит полную справочную информацию по каждой доступной команде.
  purpose: |
    Не все команды запоминаются, а со временем забываются, тем более, их аргументы и опции.
    Подобным образом можно быстро вспомнить.
  admonitions:
  others:

list-files:
  description: |
    Скрипт выводит все файлы, находящиеся в директории. +
    В результате отображается список всех файлов, удовлетворяющих требованиям фильтра.
  purpose: |
    Изначально скрипт написан для удобства создания файла `PDF_*.yml`, необходимого для генерации PDF. +
    Однако возможно использовать и для любых других целей, задав соответствующие опции.
  admonitions:
    - *path_note
  others:

reduce-images:
  description: Скрипт немного изменяет цветовую палитру и значительно уменьшает занимаемое пространство.
  purpose: |
    Для документации продуктов с графическим интерфейсом приходится делать множество скриншотов.
    При создании PDF все эти изображения добавляются, что существенно увеличивает размер файла.
  admonitions:
    - *path_note
  others:

repair-links:
  description: Скрипт проверяет и исправляет некорректные ссылки в файлах проекта, а также проверяет уникальность якорей.
  purpose: |
    Зачастую файлы перемещаются внутри проекта, удаляются, переименовываются, а ссылки на них внутри других файлов не исправляются.
    Также при задании якорей необходимо, чтобы они были уникальными в рамках всего проекта, не только отдельного файла.
  admonitions:
    - *path_note
  others: |
    == Вывод программы

    === Критические ошибки
    
    .repair_links: error: unrecognized arguments: ...
    [source,shell]
    ----
    repair_links: error: unrecognized arguments: --arg
    ----
    
    Означает, что указана не существующий ключ.
    
    .Директория ... не найдена
    [source,shell]
    ----
    InvalidDirectoryPathError, Директория path/to/dir не найдена
    ----
    
    Означает, что указана не существующая директория.
    
    .Путь ... указывает не на директорию
    [source,console]
    ----
    InvalidDirectoryPathError, Путь path/to/file указывает не на директорию
    ----
    
    Означает, что путь ведет не к директории или же является символической ссылкой.
    
    === Ошибки, требующие ручного исправления
    
    .В директории ... не найдены файлы с расширением .md, .adoc
    [source,console]
    ----
    !  В директории path/to/directory не найдены файлы с расширением .md, .adoc  ! // <1>
    ----
    
    Означает, что в директории *<1>* нет ни одного Markdown-/AsciiDoc-файла.
    
    .Внутри файла ... найдены дублирующиеся якори: ...
    [source,console]
    ----
    ---------- Не исправлено автоматически ----------
    Внутри файла content/common/path/to/file.md найдены дублирующиеся якори: // <1>
    invalid-anchor, another-invalid-anchor // <2> <3>
    -------------------------------------------------
    ----
    
    Означает, что в файле *<1>* обнаружены якори *<2>* и *<3>*, которые привязаны к нескольким местам в тексте.
    
    .Найдены повторяющиеся якори
    [source,console]
    ----
    ---------- Не исправлено автоматически ----------
    Найдены повторяющиеся якори:
    invalid-anchor // <1>
    
    Якорь invalid-anchor повторяется в файлах: // <2>
    /path/to/file.md // <3>
    /path/to/another_file.md // <4>
    -------------------------------------------------
    ----
    
    Означает, что найдены якори *<1>*, которые встречаются в различных файлах в проекте.
    Один и тот же якорь *<2>* обнаружен в файлах *<3>* и *<4>*.
    
    ****
    Почему это проблема?
    
    Дублирование якорей никак не влияет на отображение HTML, т.е. на сайте.
    Однако в PDF это нарушает работу ссылок.
    В HTML такие якори находятся на разных страницах и никак не взаимодействуют друг с другом.
    В PDF такие якори не позволяют однозначно привязать их к определенным местам в тексте.
    Ввиду этого ссылки останутся в создаваемом документе, но не будут куда-либо переходить или выполнять любое другое действие.
    ****
    
    .Якорь ... в файле ... не найден
    [source,console]
    ----
    ---------- Не исправлено автоматически ----------
    Якорь anchor в файле content/common/path/to/dest.md не найден // <1>
    -------------------------------------------------
    
    ---------- Не исправлено автоматически ----------
    В файле content/common/path/from/source.md ссылка должна быть: // <2>
    ../to/dest/#_valid_anchor_, но получено
    ../to/dest/#_anchor/
    -------------------------------------------------
    ----
    
    Означает, что в файле *<2>* есть корректная ссылка на файл *<1>*, но указан якорь, которого нет в файле *<1>*.
    
    .Не найден якорь ... в файле ...
    [source,console]
    ----
    ---------- Не исправлено автоматически ----------
    Не найден якорь anchor в файле content/common/path/file.md. // <1> <2>
    Строки: 0, 1 // <3>
    -------------------------------------------------
    ----
    
    Означает, что в файле *<2>* есть внутренняя ссылка на якорь *<1>*, которого нет в файле.
    Ссылки обнаружены в строках *<3>*.
    
    .Файл по пути ... не найден
    [source,console]
    ----
    ---------- Не исправлено автоматически ----------
    Файл по пути content/common/path/to/file.md не найден
    -------------------------------------------------
    ----
    
    Означает, что ссылка указывает на файл, находящийся вне заданной директории.
    
    .Не удалось обработать ссылку в файле
    [source,console]
    ----
    ---------- Не исправлено автоматически ----------
    Не удалось обработать ссылку в файле.
    Ссылка: ../../path/to/file/#anchor // <1>
    Файл: content/common/another/file.md // <2>
    -------------------------------------------------
    ----
    
    Означает, что в файле *<2>* обнаружен текст *<1>*, попадающий под паттерн ссылки, но имеющий синтаксическую ошибку, которая не позволяет обработать этот текст далее.
    
    === Предупреждения и оповещения
    
    .!  В файле ... ссылка должна быть
    [source,console]
    ----
    !  В файле content/common/path/to/file.md ссылка должна быть: // <1>
    ../../another/file/#anchor, но получено // <2>
    ../and_another/file/#anchor/  ! // <3>
    ----
    
    Означает, что в файле *<1>* обнаружена некорректная ссылка *<3>*, но удалось ее автоматически исправить на верную ссылку *<2>*.
    
    .Проверка дублирования якорей отключена пользователем
    ----
    Проверка дублирования якорей отключена пользователем
    ----
    
    Означает, что якори не анализируются.
    
    NOTE: Отображается только при отсутствии опции `-a`/`--anchor-disable`.
    
    .{two-colons}Изменено{two-colons}Файл
    [source,console]
    ----
    ::Изменено::Файл content/common/path/to/file.md: // <1>
    ../and_another/file/#anchor/ -> ../../another/file/#anchor // <2> <3>
    ----
    
    Означает, что в файле *<1>* ссылка *<2>* заменена на ссылку *<3>*.
    
    .Файл ... записан
    [source,console]
    ----
    Файл content/common/path/to/file.md записан // <1>
    ----
    
    Означает, что содержимое файла *<1>* обновлено.
    
    NOTE: Отображается только при отсутствии опции `-d`/`--dry-run`.
    
    .Работа завершена
    [source,console]
    ----
    Работа завершена.
    ----
    
    Означает, что работа скрипта остановлена штатно.
    
    .Файлы не изменены
    [source,console]
    ----
    ==================== Файлы не изменены ====================
    ----
    
    Означает, что отображенные изменения не были применены.
    
    NOTE: Отображается только при использовании опции `-d`/`--dry-run`.
    
    === Некоторые особенности работы
    
    * Проверяются только Markdown- и AsciiDoc-файлы, все остальные (+*+.txt, без расширения, ...) игнорируются.
    * При использовании в операционной системе Windows скрипт должен располагаться на том же диске (томе), что и директория, для которой он используется.
    Не устранимо ввиду принципов работы операционной системы.
    * Ссылки, которые указывают на файлы, находящиеся не в заданной директории, помечаются как некорректные.
    * Ссылки, начинающиеся с `http`, `mailto` и `/` игнорируются.
    * Нумерация строк начинается с 0.

repair-svg:
  description: |
    Скрипт исправляет файлы SVG, которые некорректно отображаются при конвертации в PDF. +
    В результате получаются пригодные файлы.
  purpose: |
    На данный момент сборка осуществляется с помощью AsciiDoc, в частности, с помощью библиотеки `asciidoctor-pdf`.
    Она использует для обработки изображений библиотеку `prawn`, которая не может корректно работать с некоторыми изображениями, в частности, с теми, что оперируют внешними ссылками `<foreignObject />`.
  admonitions:
    - *path_note
  others:

set-table-cols:
  description: Скрипт задает ширины столбцов в таблицах файлов AsciiDoc, если не задана опция `[cols=""]`.
  purpose: |
    Если для таблицы не указаны параметры столбцов, то при обработке процессором столбцы имеют одинаковые ширины.
    Немного существует таких таблиц, для которых такая конфигурация наиболее актуальная и подходящая.
  admonitions:
    - *path_note
  others: |
    == Принцип работы Analyzer
    
    . Для каждой ячейки вычислить минимальную ширину, необходимую для размещения текста без вынужденных разрывов.
    +
    NOTE: Ширина не может быть меньше, чем `--min-column`.
    +
    . Для каждого столбца вычислить минимальную ширину, равную максимуму из минимальных ширин ячеек.
    . Для каждой ячейки вычислить рекомендуемую ширину, необходимую для размещения текста в одну строку.
    . Для каждого столбца вычислить рекомендуемую ширину, равную максимуму из рекомендуемых ширин ячеек.
    . Для таблицы вычислить минимальную ширину, равную сумме минимальных ширин столбцов.
    . Проверить, что минимальная ширина не превышает `--max-symbols`.
    . Столбцам, в которых нет ячеек с табуляцией, задать ширину, равную их рекомендуемой.
    +
    NOTE: В таких столбцах минимальная ширина равна рекомендуемой.
    +
    . Остальным столбцам задать ширину, равную их минимальной.
    +
    NOTE: Минимальная и рекомендуемая ширина столбца не может быть меньше, чем `--min-column`.
    +
    . Если сумма заданных ширин меньше максимально допустимой, то определить доступный остаток.
    . Рассчитать доли для столбцов, пропорциональные рекомендуемым ширинам за вычетом уже заданных величин.
    . Добавить к каждой ширине столбцов долю от доступного остатка.

substitute:
  description: Скрипт подставляет значения из таблицы соответствий.
  purpose: |
    В файлах AsciiDoc имеется возможность задать переменные с помощью инструментов из коробки.
    С помощью скрипта можно упростить и ускорить обработку файла.
  admonitions:
    - *path_note
  others:

validate-yaml:
  description: |
    Скрипт проверяет корректность секций и всех путей в файле `PDF_*.yml`. +
    В результате отображается информация, есть ли проблемы с параметрами секций и файлами, и если они есть, то где именно. +
    Для секций показывается некорректно заданный параметр, некорректный тип значения параметра, отсутствие обязательного параметра или отсутствие обязательной секции.
    +
    [source,console]
    ----
    Отсутствует раздел <part>
    Раздел <part> должен быть типа object, но получено <type>
    В разделе <part> отсутствует секция <section>
    В секции <part>::<section> отсутствует ключ <key>
    ----
  purpose: |
    Изначально скрипт написан для проверки файла `PDF_*.yml`, необходимого для генерации PDF. +
    Ввиду того, что генерация PDF осуществляется целой партией, bundle, то ошибка с одним проектом ведет к отбою обновления всех других.
  admonitions:
    - *path_note
  others:
