# -*- coding: utf-8 -*-
from typing import Iterable

from utilities.common.shared import StrPath


class AsciiDocTableTerms:
    def __init__(self, lines: Iterable[str] = None) -> None: ...

    @classmethod
    def from_file(cls, file_path: StrPath): ...

    def set_terms(self) -> None: ...

    def __getitem__(self, item): ...

    def get(self, item): ...

    def __contains__(self, item) -> bool: ...

    def __len__(self) -> int: ...

    def __iter__(self): ...

    def terms_short(self) -> tuple[str, ...]: ...

    @property
    def max_row(self) -> int: ...

    def complete(self) -> None: ...

    @property
    def dict_terms(self): ...
