# -*- coding: utf-8 -*-
from typing import NamedTuple

from utilities.common.shared import StrPath


class ContentGitPage(NamedTuple):
    project_id: int | str = ...
    file_name: str = ...
    path: StrPath = ...
    content: list[str] = ...

    def __iter__(self): ...

    def validate(self): ...

    def set_content(self) -> None: ...

    def __len__(self) -> int: ...

    def __bool__(self) -> bool: ...

    def download(self) -> None: ...
