# -*- coding: utf-8 -*-
from typing import NamedTuple


class Term(NamedTuple):
    short: str | None = ...
    full: str | None = ...
    rus: str | None = ...
    commentary: str | None = ...

    def __bool__(self) -> bool: ...

    def abbr(self) -> str: ...

    def adoc(self) -> str: ...

    def formatted(self) -> str: ...


class TableCellCoordinate(NamedTuple):
    row_index: int
    column_index: int

    def __eq__(self, other): ...

    def __ne__(self, other): ...

    def __lt__(self, other): ...

    def __gt__(self, other): ...

    def __le__(self, other): ...

    def __ge__(self, other): ...

    def __bool__(self) -> bool: ...


class TableItem(NamedTuple):
    row_index: int = ...
    column_index: int = ...
    text: str | None = ...

    @property
    def coord(self) -> TableCellCoordinate: ...

    def __bool__(self) -> bool: ...

    def __eq__(self, other): ...

    def __ne__(self, other): ...

    def __lt__(self, other): ...

    def __gt__(self, other): ...

    def __le__(self, other): ...

    def __ge__(self, other): ...
