[general]
separator = "===================================================================================================="
debug_log_folder = "_logs/cli_debug.log"
log_folder = "~/Desktop/_logs/cli_debug.log"
config_path = "sources/dict.yaml"
col_max = 52
max_content_width = 96
terminal_width = 96

[update]
auto_update = true
env_var = "_TW_UTILITIES_UPDATE"
temp_dir = "~/_temp/"
temp_command_file = "~/_temp/input_command"
project_id = 65722828

[commands.shared]
directory = "!None"
files = []
verbose = false
recursive = true
dry_run = false
output = "!None"
keep_logs = false

[commands.convert-tables]
tables_dir = "./tables/"
temp_dir = "./_temp/"
escape = true
remove = false
fix = "!None"
keep = "!None"

[commands.format-code]
length = 84

[commands.repair-links]
result_file_path = "./results.txt"
anchor_validation = true
no_result = false
separate_languages = true
skip_en = false

[commands.list-files]
ignored_dirs = [
  "temp_folder",
  "_temp_folder",
  "private"
]
all_dirs = false
ignored_files = [
  "README"
]
all_files = false
extensions = "md adoc"
all_extensions = false
language = "!None"
all_languages = true
ignore_index = false
prefix = "!None"
no_prefix = false
hidden = false

[commands.set-table-cols]
max_symbols = 72
min_column = 4
add_options = true
coefficient = 1.0

[commands.get-terms]
sources = "sources/"
info_file = "help.txt"
readme_file = "readme.txt"
samples_file = "samples.txt"
project_id = 57022544
all_flag = false
full_flag = false
info_flag = false
readme_flag = false
samples_flag = false
abbr_flag = false
ascii_flag = false
common_flag = false

[commands.validate-yaml]
cutoff = 0.75
guess = true