general:
  separator: "===================================================================================================="
  debug_log_folder: "./_logs/"
  log_path: "~/Desktop/_logs/"
  config_path: "sources/dict.yaml"
  temp_dir: "~/_temp/"
  col_max: 56
  max_content_width: 100
  terminal_width: 100

update:
  auto_update: true
  env_var: "_TW_UTILITIES_UPDATE"
  temp_dir: "~/_temp/"
  temp_command_file: "~/_temp/input_command"
  project_id: 65722828

commands:
  shared:
    debug: false
    directory: null
    temp_dir: "~/_temp/"
    files: [ ]
    verbose: false
    recursive: true
    dry_run: false
    output: null
    keep_logs: false

  convert-tables:
    tables_dir: "./tables/"
    escape: true
    remove: false
    fix: null
    keep: null

  format-code:
    length: 84

  repair-links:
    result_file_path: "./results.txt"
    anchor_validation: true
    no_result: false
    separate_languages: true
    skip_en: false

  list-files:
    ignored_dirs:
      - "temp_folder"
      - "_temp_folder"
      - "temp_dir"
      - "_temp_dir"
      - "private"
    all_dirs: false
    ignored_files:
      - "README"
      - "_check_list"
    all_files: false
    extensions: "md adoc"
    all_extensions: false
    language: null
    all_languages: true
    ignore_index: false
    prefix: null
    no_prefix: false
    hidden: false

  set-table-cols:
    max_symbols: 72
    min_column: 4
    add_options: true
    coefficient: 1.0

  get-terms:
    sources: "sources/"
    info_file: "help.txt"
    readme_file: "src.txt"
    samples_file: "samples.txt"
    project_id: 57022544
    terms_file: "terms.adoc"
    version_file: "__version__.txt"
    all_flag: false
    full_flag: false
    info_flag: false
    readme_flag: false
    samples_flag: false
    abbr_flag: false
    ascii_flag: false
    common_flag: true

  validate-yaml:
    cutoff: 0.75
    guess: true
    file_beginnings:
      - "protei"
      - "pdf"

  check:
    cutoff: 0.75
    guess: true
    file_beginnings:
      - "protei"
      - "pdf"

  yaml:
    cutoff: 0.75
    guess: true
    file_beginnings:
      - "protei"
      - "pdf"

  generate-yaml:
    args: null
    dry_run: false
    language: "ru"
    outlinelevels: 4
    sectnumlevels: 4
    toclevels: 3