:asciidoctorconfigdir: ../..

[source,console,subs="attributes+"]
----
{name} link-repair {mme}

Найдены повторяющиеся якори:
balancer
src-port

Якорь balancer повторяется в файлах:
content/common/config/sgsap.md
content/common/config/s1ap.md
--------------------------------------------------------------------------------
Якорь src-port повторяется в файлах:
content/common/config/component/diameter.md
content/common/config/component/sgsap.md

balancer -> balancer-sgsap, в файле content/common/config/sgsap.md в строках: [24, 99]

balancer -> balancer-s1ap, в файле content/common/config/s1ap.md в строках: [20, 21, 53]

src-port -> src-port-diameter, в файле content/common/config/component/diameter.md в строках: [71, 228, 230, 242]

src-port -> src-port-sgsap, в файле content/common/config/component/sgsap.md в строках: [40]

Не найден якорь imsi-rules в файле content/common/config/plmn.md
Ссылка ../../config/plmn/#imsi-rules в файле content/common/oam/add_imsi.md

Не найден якорь detach_by_imsi_prefix в файле content/common/oam/api.md.
Строки: 54

В файле content/common/config/s1ap.md найден якорь
sctp-additional-info вместо sctp_additional_info

sctp_additional_info -> sctp-additional-info, в файле content/common/config/s1ap.md в строках: 22

sctp_additional_info -> sctp-additional-info, в файле content/common/config/s1ap.md в строках: 23

Файл content/common/config/s1ap.md:
sctp_additional_info -> sctp-additional-info

Не найден якорь metrics в файле content/common/config/metrics.md.
Строки: 46, 57, 48, 37, 59, 50, 61, 52, 54, 45, 56, 60, 47, 58, 51, 49, 62, 55, 53

Не найден якорь max-connection-count в файле content/common/config/ap.md.
Строки: 109

Не найден якорь application-address в файле content/common/config/ap.md.
Строки: 108

Не найден якорь cyclic-walk-tree в файле content/common/config/ap.md.
Строки: 115

В файле content/common/config/component/diameter.md ссылка должна быть:
../../../oam/system_management/, но получено
../../oam/system_management/

../../oam/system_management/ -> ../../../oam/system_management/, в файле content/common/config/component/diameter.md в строках: 9

Не найден якорь origin-host-diam в файле content/common/config/diameter.md
Ссылка ../../diameter/#origin-host-diam в файле content/common/config/component/diameter.md

Не найден якорь origin-realm-diam в файле content/common/config/diameter.md
Ссылка ../../diameter/#origin-realm-diam в файле content/common/config/component/diameter.md

Не найден якорь replace-origin-identities в файле content/common/config/diameter.md
Ссылка ../../diameter/#replace-origin-identities в файле content/common/config/component/diameter.md

Не найден якорь appl-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#appl-timeout в файле content/common/config/component/diameter.md

Не найден якорь watchdog-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#watchdog-timeout в файле content/common/config/component/diameter.md

Не найден якорь reconnect-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#reconnect-timeout в файле content/common/config/component/diameter.md

Не найден якорь on-busy-reconnect-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#on-busy-reconnect-timeout в файле content/common/config/component/diameter.md

Не найден якорь on-shutdown-reconnect-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#on-shutdown-reconnect-timeout в файле content/common/config/component/diameter.md

Не найден якорь response-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#response-timeout в файле content/common/config/component/diameter.md

Не найден якорь breakdown-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#breakdown-timeout в файле content/common/config/component/diameter.md

Не найден якорь statistic-timeout в файле content/common/config/diameter.md
Ссылка ../../diameter/#statistic-timeout в файле content/common/config/component/diameter.md

Не найден якорь local_host в файле content/common/config/diameter.md
Ссылка ../../diameter/#local_host в файле content/common/config/component/diameter.md

Не найден якорь local_port в файле content/common/config/diameter.md
Ссылка ../../diameter/#local_port в файле content/common/config/component/diameter.md

Не найден якорь local_interfaces в файле content/common/config/diameter.md
Ссылка ../../diameter/#local_interfaces в файле content/common/config/component/diameter.md

Не найден якорь local_host в файле content/common/config/diameter.md
Ссылка ../../diameter/#local_host в файле content/common/config/component/diameter.md

Не найден якорь local_host в файле content/common/config/diameter.md
Ссылка ../../diameter/#local_host в файле content/common/config/component/diameter.md

Не найден якорь peer-table в файле content/common/config/component/sgsap.md.
Строки: 18

В файле content/common/config/component/sgsap.md ссылка должна быть:
../../../oam/system_management/, но получено
../../oam/system_management/

../../oam/system_management/ -> ../../../oam/system_management/, в файле content/common/config/component/sgsap.md в строках: 12

Не удалось обработать ссылку в файле.
Ссылка: ../served_plmn/#mcc
Файл: content/common/config/rules/rac_rules.md

Не удалось обработать ссылку в файле.
Ссылка: ../served_plmn/#mnc
Файл: content/common/config/rules/rac_rules.md

Не найден якорь imsiRules в файле content/common/config/plmn.md
Ссылка ../../plmn/#imsiRules в файле content/common/config/rules/imsi_rules.md

В файле content/common/config/plmn.md найден якорь
tac_rules вместо tac-rules

В файле content/common/config/plmn.md найден якорь
tac_rules вместо tac-rules

Не найден якорь imsi-rules-imsi в файле content/common/config/rules/imsi_rules.md
Ссылка ../imsi_rules/#imsi-rules-imsi в файле content/common/config/rules/tac_rules.md

Не найден якорь pgw_served_plmn в файле content/common/config/plmn.md
Ссылка ../../plmn/#pgw_served_plmn в файле content/common/config/rules/apn_rules.md

Не найден якорь gtp-c-edr в файле content/common/logging/edr/gtp_c.md
Ссылка ../gtp_c/#gtp-c-edr в файле content/common/logging/edr/connect.en.adoc

Не найден якорь error-codes в файле content/common/logging/edr/error_code.md
Ссылка ../error_code/#error-codes в файле content/common/logging/edr/tau.en.adoc

Не найден якорь diam-edr в файле content/common/logging/edr/diam.md
Ссылка ../diam/#diam-edr в файле content/common/logging/edr/tau.en.adoc

Не удалось обработать ссылку в файле.
Ссылка: ../../../config/diam_dest/#dest-realm
Файл: content/common/logging/stat/MME_Diameter.md

Работа завершена.

==================== Файлы изменены ====================
----