# -*- coding: utf-8 -*-
class BaseError(Exception): ...


class InvalidPythonVersion(BaseError): ...


class TimerError(BaseError): ...


class TimerRunningError(TimerError): ...


class TimerStoppedError(TimerError): ...


class TermsError(BaseError): ...


class TermsRequiredAttributeMissingError(TermsError): ...


class TermsAsciiDocFileTableRowIndexError(TermsError): ...


class TermsInvalidProjectIdError(TermsError): ...


class TermsInvalidVersionError(TermsError): ...


class TermsInvalidTermIndexError(TermsError): ...


class TermsEmptyFileError(TermsError): ...


class TermsInvalidTypeVersionError(TermsError): ...


class LinkRepairError(BaseError): ...


class LinkRepairLineInvalidTypeError(LinkRepairError): ...


class LinkRepairInvalidStorageAttributeError(LinkRepairError): ...


class LinkRepairInvalidFileDictAttributeError(LinkRepairError): ...


class LinkRepairFileInvalidTypeError(LinkRepairError): ...


class LinkRepairInternalLinkAnchorError(LinkRepairError): ...


class LinkRepairInvalidMatchError(LinkRepairError): ...


class LinkRepairFixerNoLinkError(LinkRepairError): ...


class LinkRepairInvalidHashCharIndexError(LinkRepairError): ...


class LinkRepairMissingFileError(LinkRepairError): ...


class ConvertTablesError(BaseError): ...


class ConvertTablesEmptyLinesError(ConvertTablesError): ...


class FormatCodeError(BaseError): ...


class FormatCodeNonPositiveLineLengthError(FormatCodeError): ...


class FormatCodeNonIntegerLineLengthError(FormatCodeError): ...


class TableColsError(BaseError): ...


class TableColsTableBorderNotClosedError(TableColsError): ...


class TableColsTableCoordinateInitError(TableColsError): ...


class TableColsTableColumnTypeError(TableColsError): ...


class TableColsTableColumnIndexError(TableColsError): ...


class TableColsTableColumnInvalidNameError(TableColsError): ...


class TableColsTableColumnInvalidIdentifierError(TableColsError): ...


class NoArgumentsOptionsError(BaseError): ...
