= Описание программы
:author: Andrew Tar
:email: andrew.tar@yahoo.com
:revdate: Jul 3, 2023
:revnumber: 1.1.0
:experimental:
:icons: font
:toc: auto
:toclevels: 5
:toc-title: Содержание
:source-highlighter: rouge

== Краткое описание

Утилита для получения полного наименования сокращения и его описания.

== Принцип работы

Используется таблица, хранящаяся в https://gitlab.com/tech_writers_protei/info/-/blob/main/terms.adoc[репозитории] Gitlab. +
Из ввода пользователя вычленяются термины, а затем осуществляется попытка их найти в указанной таблице.

== Правила ввода

Искомые термины и аббревиатуры можно вводить как по одному, так и несколько. +
При вводе нескольких необходимо отделить друг от друга любым не циферным и не буквенным символом, кроме '_' и '-'. +
Ввод не чувствителен к регистру символов.

== Вывод ответа на запрос

Если ввод корректный, и термины известны, то для каждого выводится:

* Сокращение на английском языке;
* Расшифровка сокращения на английском языке (при наличии);
* Расшифровка сокращения на русском языке (при наличии);
* Комментарий на русском языке (при наличии).

=== Формат вывода

[source,console]
----
<сокращение>
<термин полностью>, <перевод термина> — <русское описание>
-------------------------------------------------------------------------------------------------
----

.Пример вывода
[source,console]
----
BFCP
Binary Floor Control Protocol, протокол управления на двоичном уровне — протокол для обмена презентациями во время видеоконференций
-------------------------------------------------------------------------------------------------
----

== Специальные запросы

В программе предусмотрены особые запросы для получения информации о словаре:

* *-a*/*--all* -- вывод всех терминов и сокращений на английском;
* *-f*/*--full* -- вывод всех терминов и сокращений, а также их полные расшифровки и комментарии;
* *-h*/*--help* -- вывод краткой справочной информации;
* *-r*/*--readme* -- вывод полной справочной информации из файла readme.txt;
* *-s*/*--samples* -- вывод примеров использования;

NOTE: Чтобы отобразить термин в виде, пригодном для вставки в качестве всплывающей подсказки, используется опция *--abbr*:

[source,console]
----
--abbr IMSI IMEI

<abbr title="International Mobile Subscriber Identifier">IMSI</abbr>
<abbr title="International Mobile Equipment Identifier">IMEI</abbr>
-------------------------------------------------------------------------------------------------
----

== Логирование

Журнал выполнения программы записывается в директорию +
menu:HOME[Desktop > _terms_logs > terms_debug.log].

По умолчанию, директория удаляется, если работа программы завершилась в штатном режиме.
При возникновении ошибки директория остается, и в дальнейшем будет использоваться для исправления некорректной обработки сценария.

Для сохранения директории и лог-файла необходимо добавить переменную окружения *KEEP_TERMS_LOGS* с любым значением.

== Пример работы

=== Сокращение с одним значением

Вывод: *Значение сокращения*

[source,console]
----
PC
Protocol Class, класс протокола
-------------------------------------------------------------------------------------------------
----

=== Сокращение с несколькими значениями

Вывод: *Все значения сокращения*

[source,console]
----
LAC
L2TP Access Concentrator, концентратор доступа L2TP
Local Area Code, код локальной зоны
-------------------------------------------------------------------------------------------------
----

== Неизвестное сокращение

Вывод: *Не найдено*

[source,console]
----
QWE
Не найдено
-------------------------------------------------------------------------------------------------
----

=== Ввод нескольких известных сокращений

Вывод: *Все значения известных сокращений*

[source,console]
----
SCP SRF;DPC/ASP
SCP
Service Control Point, модуль логик услуг, реализованных посредством протокола CAMEL
SRF
Signaling Relay Function, функция ретрансляции сигнальных сообщений
DPC
Destination Point Code, код сигнальной точки назначения
ASP
Application Server Process, отдельный экземпляр AS SIGTRAN
ASP
Application Service Provider, поставщик услуг доступа к приложениям
-------------------------------------------------------------------------------------------------
----

=== Ввод нескольких корректных сокращений, среди которых есть неизвестные

Вывод: *Все значения известных сокращений, все неизвестные пропускаются*

[source,console]
----
LCS LI LOS
LCS
Location Service, служба определения местоположения
LI
Legal Intervention, законное вмешательство в вызов
LI
Length Indicator, индикатор длины
LI
Log Intelligence, обработка лог-файлов
-------------------------------------------------------------------------------------------------
----

=== Некорректный ввод

Вывод: *Не найдено*

[source,console]
----
~A
Не найдено
-------------------------------------------------------------------------------------------------
----

=== Выход

[source,console]
----
__exit__
Программа остановлена пользователем
Нажмите любую клавишу, чтобы закрыть окно ...
----
