= Описание программы
:author: Andrew Tar
:email: andrew.tar@yahoo.com
:revdate: Jul 3, 2023
:revnumber: 1.1.0
:experimental:
:icons: font
:toc: auto
:toclevels: 5
:toc-title: Содержание
:source-highlighter: rouge

== Краткое описание

Утилита для получения полного наименования сокращения и его описания.

== Принцип работы

Используется таблица, хранящаяся в https://gitlab.com/tech_writers_protei/info/-/blob/main/terms.adoc[репозитории] Gitlab. +
Из ввода пользователя вычленяются термины, а затем осуществляется попытка их найти в указанной таблице.

== Правила ввода

Искомые термины и аббревиатуры можно вводить как по одному, так и несколько. +
При вводе нескольких необходимо отделить друг от друга любым не циферным и не буквенным символом, кроме '_' и '-'. +
Ввод не чувствителен к регистру символов.

== Вывод ответа на запрос

Если ввод корректный, и термины известны, то для каждого выводится:

* Сокращение на английском языке;
* Расшифровка сокращения на английском языке (при наличии);
* Расшифровка сокращения на русском языке (при наличии);
* Комментарий на русском языке (при наличии).

=== Формат вывода

[source,console]
----
<сокращение>
<термин полностью>, <перевод термина> — <русское описание>
-------------------------------------------------------------------------------------------------
----

.Пример вывода
[source,console]
----
BFCP
Binary Floor Control Protocol, протокол управления на двоичном уровне — протокол для обмена презентациями во время видеоконференций
-------------------------------------------------------------------------------------------------
----

== Специальные запросы

В программе предусмотрены особые запросы для получения информации о словаре:

* *-a*/*--all* -- вывод всех терминов и сокращений на английском;
* *-f*/*--full* -- вывод всех терминов и сокращений, а также их полные расшифровки и комментарии;
* *-h*/*--help* -- вывод краткой справочной информации;
* *-r*/*--readme* -- вывод полной справочной информации из файла readme.txt;
* *-s*/*--samples* -- вывод примеров использования;

NOTE: Чтобы отобразить термин в виде, пригодном для вставки в качестве всплывающей подсказки, используется опция *--abbr*:

[source,console]
----
--abbr IMSI IMEI

<abbr title="International Mobile Subscriber Identifier">IMSI</abbr>
<abbr title="International Mobile Equipment Identifier">IMEI</abbr>
-------------------------------------------------------------------------------------------------
----

== Логирование

Журнал выполнения программы записывается в директорию +
menu:HOME[Desktop > _terms_logs > terms_debug.log].

По умолчанию, директория удаляется, если работа программы завершилась в штатном режиме.
При возникновении ошибки директория остается, и в дальнейшем будет использоваться для исправления некорректной обработки сценария.

Для сохранения директории и лог-файла необходимо добавить переменную окружения *KEEP_TERMS_LOGS* с любым значением.

== Выход из программы

Для выхода необходимо ввести любой из ниже предложенных вариантов (без кавычек):

[source,console]
----
__exit__
exit
__quit__
quit
!e
!exit
!q
!quit
----

== Пример работы

* Запуск программы

[source,console]
----
C:\Users\...\venv\venv\Scripts\python.exe

В случае ошибки необходимо сохранить лог-файл, который будет находиться здесь:
C:\Users\user\PycharmProjects\terms_mine\terms\logs

...

Для выхода необходимо ввести любой из нижепредложенных вариантов (без кавычек):
__exit__, exit, __quit__, quit, !e, !exit, !q, !quit
----

* Строка для ввода значений

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
----

=== Сокращение с одним значением

Вывод: *Значение сокращения*

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
PC
Protocol Class, класс протокола
-------------------------------------------------------------------------------------------------
----

=== Сокращение с несколькими значениями

Вывод: *Все значения сокращения*

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
LAC
L2TP Access Concentrator, концентратор доступа L2TP
Local Area Code, код локальной зоны
-------------------------------------------------------------------------------------------------
----

== Неизвестное сокращение

Вывод: *Не найдено*

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
QWE
Не найдено
-------------------------------------------------------------------------------------------------
----

=== Ввод нескольких известных сокращений

Вывод: *Все значения известных сокращений*

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
SCP SRF;DPC/ASP
SCP
Service Control Point, модуль логик услуг, реализованных посредством протокола CAMEL
SRF
Signaling Relay Function, функция ретрансляции сигнальных сообщений
DPC
Destination Point Code, код сигнальной точки назначения
ASP
Application Server Process, отдельный экземпляр AS SIGTRAN
ASP
Application Service Provider, поставщик услуг доступа к приложениям
-------------------------------------------------------------------------------------------------
----

=== Ввод нескольких корректных сокращений, среди которых есть неизвестные

Вывод: *Все значения известных сокращений, все неизвестные пропускаются*

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
LCS LI LOS
LCS
Location Service, служба определения местоположения
LI
Legal Intervention, законное вмешательство в вызов
LI
Length Indicator, индикатор длины
LI
Log Intelligence, обработка лог-файлов
-------------------------------------------------------------------------------------------------
----

=== Некорректный ввод

Вывод: *Не найдено*

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
~A
Не найдено
-------------------------------------------------------------------------------------------------
----

=== Выход

[source,console]
----
Введите сокращение или несколько сокращений, чтобы получить полное наименование и описание:
__exit__
Программа остановлена пользователем
Нажмите любую клавишу, чтобы закрыть окно ...
----

== Исходные файлы

NOTE: При использовании файлов terms/terms.exe информация из этого раздела не требуется.
Приведена для случаев внесения изменений в программу.

Для использования исходных файлов необходимо создать клон проекта.

[source,bash]
----
git clone git@gitlab.com:tech_writers_protei/terms.git
----

== Структура файлов проекта

....
terms/
  ├─bin/
  | ├─terms
  | └─terms.exe
  |
  ├─sources/
  | ├─help.txt
  | ├─readme.txt
  | └─samples.txt
  |
  ├─terms/
  | ├─__init__.py
  | ├─ascii_doc_table_terms.py
  | ├─const.py
  | ├─content_git_page.py
  | ├─custom_exceptions.py
  | ├─git_manager.py
  | ├─http_request.py
  | ├─init_logger.py
  | ├─main.py
  | ├─table.py
  | ├─user_input.py
  | └─version_container.py
  |
  ├─tests/
  | ├─src/
  | | └─ascii_doc_table_terms.adoc
  | |
  | ├─__init__.py
  | ├─conftest.py
  | ├─test_user_input.py
  | └─test_user_input_parser.py
  |
  ├─.editorconfig
  ├─.gitignore
  ├─.gitlab-ci.yml
  ├─.pre-commit-config.yaml
  ├─__main__.py
  ├─LICENSE
  ├─make_file.sh
  ├─MANIFEST.in
  ├─manual.adoc
  ├─poetry.lock
  ├─pyproject.toml
  ├─README.adoc
  ├─terms.exe.spec
  └─terms.spec
....

=== Используемые директории

* *bin* -- исполняемые файлы;
* *sources* -- дополнительные файлы, используемые в ходе работы;
* *terms* -- файлы исходного кода;
* *tests* -- файлы тестов;

==== Файлы директории bin

* *terms* -- исполняемый файл для *nix-подобных систем;
* *terms.exe* -- исполняемый файл для Windows;

==== Файлы директории sources

* *help.txt* -- текст при вызове краткой информации (опции -a/--all);
* *readme.txt* -- текст при вызове полной информации (опции -r/--readme);
* *samples.txt* -- текст при вызове примеров использования (опции -s/--samples).

==== Файлы директории terms

* *+__init__.py+* -- файл для создания пакета;
* *ascii_doc_table_terms.py* -- файл для работы с файлами AsciiDoc;
* *const.py* -- файл для хранения общих констант, используемых различными файлами;
* *content_git_page.py* -- файл для обработки загруженных файлов Git;
* *custom_exceptions.py* -- файл для хранения пользовательских исключений и ошибок;
* *git_manager.py* -- файл для работы с загруженными файлами Git;
* *http_request.py* -- файл для работы с HTTP-запросами и обработки файлов, передаваемых по HTTP;
* *init_logger.py* -- файл для настройки ведения логов;
* *main.py* -- основной файл, собирающий воедино компоненты и реализующий бизнес-логику;
* *table.py* -- файл для работы с таблицами;
* *user_input.py* -- файл для обработки пользовательского ввода в командную строку терминала;
* *version_container.py* -- файл для работы с файлами версий.

==== Файлы директории tests

* *sources* -- директория для хранения файлов, используемых в тестах;
** *ascii_doc_table_terms.adoc* -- файл для тестирования работы с AsciiDoc-таблицами;
* *+__init__.py+* -- файл для создания пакета;
* *conftest.py* -- файл для хранения настроек библиотеки https://docs.pytest.org/en/7.4.x/contents.html[*pytest*] и объектов, используемых в качестве fixture;
* *test_user_input.py* -- файл для тестирования методов класса UserInput;
* *test_user_input_parser.py* -- файл для тестирования методов класса UserInputParser;

=== Файлы в корневой директории пакета

* *LICENSE* -- файл лицензии;
* *MANIFEST.in* -- файл для управления не исполняемыми файлами при сборке и публикации проекта в виде пакета;
* *README.adoc* -- файл для описания проекта, который, собственно, сейчас и открыт;
* *#+__main__.py+#* -- ключевой базовый файл для активации работы программы;
* *manual.adoc* -- файл подробного руководства по использованию;
* *make_file.sh* -- файл скрипта *bash* для самостоятельной сборки пакета в исполняемый файл с помощью библиотеки https://pyinstaller.org/en/stable[*PyInstaller*];
* *poetry.lock* -- служебный файл пакета https://python-poetry.org/[*Poetry*] для работы с зависимостей;
* *pyproject.toml* -- файл для хранения параметров, используемых при сборке и публикации пакета.

== Требования к программному обеспечению и сторонние зависимости

Для работы программы необходим Python v3.7+.

Во время работы программы используются следующие PyPI-библиотеки:

* certifi;
* charset-normalizer;
* idna;
* loguru;
* more-itertools;
* pip;
* setuptools;
* urllib3;
* wheel;
* pytest, опционально (для запуска тестов).
