[[check-russian]]
= Руководство для check-russian
:experimental:
:icons: font
:source-highlighter: rouge
:imagesdir: images
:figure-caption: Рисунок
:stylesdir: ../css
:stylesheet: default.css
:nofooter:
:toc: auto
:toc-title: Содержание
:sectnums:
:name: tw_utilities.exe
:script-name: check-russian

== Описание

Скрипт проверяет наличие кириллических символов в файлах.

В результате отображается информация, найдены ли не латинские символы:

[,log]
----
В файле <path to file> <найдены/не найдены> кириллические буквы [в строках: <line no>, ..., <line no>]
----

* `path to file` -- путь до файла;
* `line no` -- номер строки в файле, где найдены кириллические символы.

include::partials/no_russian_sample.adoc[]

Поскольку в выводе возможно много строк, то для удобства ориентирования в нем используется интуитивная цветовая индикация.

CAUTION: Скрипт не показывает непереведенные слова или подмены схожих букв, это остается делом пользователя, а указывает лишь на файлы и строки, где это обнаружено.

== Для чего нужно?

При переводе вручную можно вполне себе забыть или не заметить какие-то фразы/слова/предложения, оставшиеся на русском языке.

include::partials/run.adoc[]

=== Опции скрипта

[source,console,subs="attributes"]
----
Использование:
{name} {script-name}
-f/--file <FILE> ... <FILE>
-d/--dir <DIR>
--recursive
--keep-logs

  Команда для проверки наличия непереведенных слов

Опции:
  -f, --file <FILE> ... <FILE>           Перечень файлов для обработки.
                                         Может использоваться несколько раз
  -d, --dir <DIR>                        Директория для обработки
  --recursive / --no-recursive           Флаг рекурсивного поиска файлов.
                                         По умолчанию: True, поиск файлов по вложенным папкам
  --keep-logs                            Флаг сохранения директории с лог-файлом по завершении
                                         работы в штатном режиме.
                                         По умолчанию: False, лог-файл и директория удаляются
  -h, --help                             Вывести справочную информацию на
                                         экран и завершить работу
----------------------------------------------------------------------------------------------------
----

NOTE: При указании директории в ней выбираются файлы, в которых присутствует постфикс `.en`.

NOTE: Путь может быть как абсолютным, так и относительным.
