= Руководство для no_russian.py
:experimental:
:icons: font
:source-highlighter: rouge
:imagesdir: images
:figure-caption: Рисунок
:stylesdir: ../css
:stylesheet: default.css
:nofooter:
:toc: auto
:toc-title: Содержание

== Описание

Скрипт проверяет наличие кириллических символов в файлах.

В результате отображается информация, найдены ли не латинские символы:

[,log]
----
В файле <path to file> <найдены/не найдены> кириллические буквы [в строках: <line no>, ..., <line no>]
----

* `path to file` -- путь до файла;
* `line no` -- номер строки в файле, где найдены кириллические символы.

include::partials/no_russian_sample.adoc[]

Поскольку в выводе возможно много строк, то для удобства ориентирования в нем используется интуитивная цветовая индикация.

CAUTION: Скрипт не показывает непереведенные слова или подмены схожих букв, это остается делом пользователя, а указывает лишь на файлы и строки, где это обнаружено.

== Для чего нужно?

При переводе вручную можно вполне себе забыть или не заметить какие-то фразы/слова/предложения, оставшиеся на русском языке.

== Как запустить?

Запускается так же, как и любые другие скрипты:

[source,shell]
----
$ py <path/to/no_russian.py> <OPTIONS> // <1> <2>
----

<1> path/to/no_russian.py -- путь до скрипта `no_russian.py`
<2> OPTIONS -- опции скрипта

=== Опции скрипта

NOTE: Здесь предполагается, что скрипт находится в директории, откуда запускается, +
т.е. `<path/to/no_russian.py>` -> `no_russian.py`.

[source,console]
----
Использование: py no_russian.py [ -h/--help | -v/--version ] PATH [ --no-recursive ]

Проверка наличия не переведенных слов

Обязательные:
  PATH            Путь до файла или директории

Опциональные:
  --no-recursive  Флаг отключения рекурсивного поиска файлов в подпапках. Если указан путь до файла, то игнорируется
  -v, --version   Показать версию скрипта и завершить работу
  -h, --help      Показать справку и завершить работу
----

NOTE: При указании директории в ней выбираются файлы, в которых присутствует постфикс `.en`.

NOTE: По умолчанию, поиск файлов в директории рекурсивный, т.е. включает в себя поиск и во вложенных директориях.

NOTE: Путь может быть как абсолютным, так и относительным.

TIP: Чтобы удобно и быстро получить путь до файла или директории, можно выполнить следующие шаги:

include::partials/get_path.adoc[]
