[[table-cols]]
= Руководство для table-cols
:experimental:
:icons: font
:source-highlighter: rouge
:imagesdir: images
:figure-caption: Рисунок
:stylesdir: ../css
:stylesheet: default.css
:nofooter:
:toc: auto
:toc-title: Содержание
:sectnums:
:pdf-themesdir: themes
:pdf-theme: base-theme.yml
:name: tw_utilities.exe
:script-name: table-cols

== Описание

Скрипт задает ширины столбцов в таблицах файлов AsciiDoc, если не задана опция `[cols=""]`.

== Для чего нужно?

Если для таблицы не указаны параметры столбцов, то при обработке процессором столбцы имеют одинаковые ширины.
Немного существует таких таблиц, для которых такая конфигурация наиболее актуальная и подходящая.

include::partials/run.adoc[]

=== Опции скрипта

[source,console,subs="attributes+"]
----
Использование:
{name} {script-name} PATHDIR
-f/--file FILE ... FILE | -d/--dir DIR | --recursive | -s/--max-symbols WIDTH |
-c/--min-column WIDTH | --keep-logs | --h/--help

  Команда для задания ширины столбцам таблиц

Опции:
  -f, --file FILE ... FILE               Файл для обработки. Может использоваться несколько раз
  -d, --dir DIR                          Директория для обработки
  --recursive / --no-recursive           Флаг рекурсивного поиска файлов.
                                         По умолчанию: True, поиск файлов по вложенным папкам
  -s, --max-symbols WIDTH                Максимальная ширина столбца в символах. По умолчанию: 72.
                                         Примечание. Должно быть целым положительным числом
  -c, --min-column WIDTH                 Минимальная ширина столбца в символах. По умолчанию: 4.
                                         Примечание. Должно быть целым положительным числом
  --keep-logs                            Флаг сохранения директории с лог-файлом по завершении
                                         работы в штатном режиме.
                                         По умолчанию: False, лог-файл и директория удаляются
  -h, --help                             Вывести справочную информацию на экран и завершить работу
----------------------------------------------------------------------------------------------------
----

NOTE: Путь может быть как абсолютным, так и относительным.

== Принцип работы Analyzer

. Для каждой ячейки вычислить минимальную ширину, необходимую для размещения текста без вынужденных разрывов.
+
NOTE: Ширина не может быть меньше, чем `--min-column`.
+
. Для каждого столбца вычислить минимальную ширину, равную максимуму из минимальных ширин ячеек.
. Для каждой ячейки вычислить рекомендуемую ширину, необходимую для размещения текста в одну строку.
. Для каждого столбца вычислить рекомендуемую ширину, равную максимуму из рекомендуемых ширин ячеек.
. Для таблицы вычислить минимальную ширину, равную сумме минимальных ширин столбцов.
. Проверить, что минимальная ширина не превышает `--max-symbols`.
. Столбцам, в которых нет ячеек с табуляцией, задать ширину, равную их рекомендуемой.
+
NOTE: В таких столбцах минимальная ширина равна рекомендуемой.
+
. Остальным столбцам задать ширину, равную их минимальной.
+
NOTE: Минимальная и рекомендуемая ширина столбца не может быть меньше, чем `--min-column`.
+
. Если сумма заданных ширин меньше максимально допустимой, то определить доступный остаток.
. Рассчитать доли для столбцов, пропорциональные рекомендуемым ширинам за вычетом уже заданных величин.
. Добавить к каждой ширине столбцов долю от доступного остатка.