= Руководство для repair_svg.py
:experimental:
:icons: font
:source-highlighter: rouge
:imagesdir: images
:figure-caption: Рисунок
:stylesdir: ../css
:stylesheet: default.css
:nofooter:
:toc: auto
:toc-title: Содержание

== Описание

Скрипт исправляет файлы SVG, которые некорректно отображаются при конвертации в PDF.

В результате получаются пригодные файлы.

== Для чего нужно?

На данный момент сборка осуществляется с помощью AsciiDoc, в частности, с помощью библиотеки `asciidoctor-pdf`, которая использует для обработки изображений библиотеку `prawn`, которая не может корректно работать с некоторыми изображениями.

== Как запустить?

Запускается так же, как и любые другие скрипты:

[source,shell]
----
$ py <path/to/repair_svg.py> <PATH> .. <PATH>  # <1> <2>
----

<1> path/to/repair_svg.py -- путь до скрипта `repair_svg.py`
<2> PATH -- путь до файла

=== Опции скрипта

NOTE: Здесь предполагается, что скрипт находится в директории, откуда запускается, +
т.е. `<path/to/repair_svg.py>` -> `repair_svg.py`.

[source,console]
----
Использование: py repair_svg.py [ -h/--help | -v/--version ] PATH .. PATH

Исправление SVG

Обязательные:
  PATH            Путь до SVG-файла. Может использоваться несколько раз.

Опциональные:
  -v, --version   Показать версию скрипта и завершить работу
  -h, --help      Показать справку и завершить работу
----

NOTE: Путь может быть как абсолютным, так и относительным.

TIP: Чтобы удобно и быстро получить путь до файла или директории, можно выполнить следующие шаги:

include::partials/get_path.adoc[]
