[[auto-update]]
= Механизм автообновления
:imagesdir: images
:stylesdir: ../css
:stylesheet: default.css
:toc-title: Содержание
:pdf-themesdir: themes
:pdf-theme: base-theme.yml
:asciidoctorconfigdir: ../

== Описание

В версии 2.1.0 добавлено автоматическое обновление исполняемого файла.

Проверяются:

* переменная окружения `_TW_UTILITIES_UPDATE = 0` (по умолчанию отсутствует, далее `_TW_UTILITIES_UPDATE = 1`);
* значение `auto_update = 0` в конфигурационном файле (по умолчанию `auto_update = 1`, не корректируется пользователем);
* наличие файла:
** `%LOCALAPPDATA%/_tw_utilities_update` для Windows;
** `$HOME/local/_tw_utilities_update` для *nix;
* опция `-U/--no-update` в команде (по умолчанию `--update`).

Если выполнено хотя бы одно из условий, то автообновление отключено.

Если ничего не менять, то по умолчанию автообновление включено.

Пользователь может изменить это поведение:

* задав `_TW_UTILITIES_UPDATE = 0` для переменной окружения любой области доступности: подходит как для локального пользователя, так и глобально;
* создав файл по вышеуказанному пути соответственно операционной системе, при этом содержимое полностью игнорируется, поскольку даже наличие доступа к файлу не проверяется, тем более не открывается.

Иначе осуществляется проверка текущей версии скрипта и последней версии на git в проекте https://gitlab.com/tech_writers_protei/utilities/[tech_writers_protei/utilities/].

== Переменная _TW_UTILITIES_UPDATE

Возможные значения:

* Деактивация:
+
** 0
** "0"
** no
** off

== Как отключить автоматическое обновление?

Чтобы отключить механизм, можно использовать один из методов:

. Задать деактивацию `_TW_UTILITIES_UPDATE`:
+
* Windows:
+
[source,powershell]
----
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force;
[Environment]::SetEnvironmentVariable("_TW_UTILITIES_UPDATE", "0", "User");
RefreshEnv.cmd;
----
+
* ++*++nix:
+
[source,shell]
----
$ echo "_TW_UTILITIES_UPDATE=0" >> ~/.bashrc;
$ source ~/.bashrc
----
+
. Использовать опцию -U/--no-update в команде:
* Windows:
+
[source,powershell]
----
$ .\tw_utilities.exe --no-update <command> <options>
----
* ++*++nix:
+
[source,shell]
----
$ tw_utilities --no-update <command> <options>
----
+
. Разорвать соединение с Интернетом, чтобы запросы к репозиторию git были неуспешными.
. Создать пустой файл:
+
* Windows:
+
[source,powershell]
----
$filePath = Join-Path $env:LOCALAPPDATA "_tw_utilities_update"
New-Item -ItemType File -Path $filePath -Force | Out-Null
----
+
*nix:
+
[source,shell]
----
$ touch $HOME/local/_tw_utilities_update
----