[[generate-yaml]]
= Руководство для generate-yaml
:imagesdir: images
:stylesdir: ../css
:stylesheet: default.css
:pdf-themesdir: themes
:pdf-theme: base-theme.yml
:script-name: validate-yaml
:asciidoctorconfigdir: ..

== Описание

Скрипт генерирует файл `PDF_*.yml` для создания PDF.

В результате записывается файл `PDF_<title-page>.yml` для русского языка и `PDF_<title-page>.<language>.yml` для иностранного языка, который следует структуре проекта.

При этом учитывается вес файлов и не включаются черновые файлы.

CAUTION: Файл записывается в директорию указанного проекта.

== Для чего нужно?

В проекте может быть большое количество файлов в разных статусах.
Проекты могут иметь большой уровень вложенности.
Не всегда удается вручную отсеять нужное для заполнения `PDF_*.yml`.

include::partials/run.adoc[]

=== Опции скрипта

[source,console,subs="attributes+"]
----
Использование:
{name} {script-name} <PROJECT>
-t/--title-page <TITLE> | -v/--version <VERSION> | -d/--dry-run | -l/--language <LANG> |
-a/--args <KEY>=<VALUE> | -k/--keep-logs | --h/--help

  Команда для генерации YAML-файла, используемого при сборке PDF

Аргументы:
  project (*)                            Путь до директории проекта

Опции:
  -t, --title-page <TITLE> (*)           Название продукта, отображаемое на титульном листе
  -v, --version <VERSION> (*)            Номер версии продукта
  -d, --dry-run / -D, --no-dry-run       Флаг вывода текста на экран без записи в файл
                                         в директории проекта.
                                         По умолчанию: False, файл создается
  -l, --language <LANG>                  Используемый язык в файлах.
                                         Возможные значения: ru, en, fr. По умолчанию: ru
  -a, --args <KEY>=<VALUE>               Дополнительные параметры AsciiDoc, добавляемые к файлу,
                                         или изменяющие значения по умолчанию.
                                         По умолчанию: null
  {keep-logs}
                                         {keep-logs-cont}
                                         {keep-logs-default}
  {help}
                                         {help-cont}
------------------------------------------------------------------------------------------------
----

NOTE: Путь может быть как абсолютным, так и относительным.

WARNING: Файлы, чье имя начинается с `.` или `_` игнорируются, поскольку это, как правило, временные или служебные файлы, к тому же игнорируемые всеми генераторами статических сайтов.

=== Примеры

include::partials/generate-yaml.adoc[]