= Инструкция по использованию
:author: Andrew Tar
:email: andrew.tar@yahoo.com
:revdate: Jul 28, 2024
:revnumber: 1.1.0
:experimental:
:icons: font

Здесь приведена сокращенная информация о работе и запуске программы.
Полная инструкция приведена в руководстве xref:manual.adoc[manual.adoc].

== Алгоритм для использования программы

. Загрузить файл `terms.exe`.
. Запустить загруженный файл двойным нажатием левой кнопки мыши.
. Изучить краткую инструкцию, выведенную в консольное окно.
. В консольном окне указать один или несколько терминов, разделенные любым не буквенным и не цифровым символом, кроме `_` и `-`, или одну из предусмотренных опций:
+
* `-a`/`--all` -- вывод всех терминов и сокращений на английском;
* `-f`/`--full` -- вывод всех терминов и сокращений, а также их полные расшифровки и комментарии;
* `-h`/`--help` -- вывод краткой справочной информации;
* `-r`/`--readme` -- вывод полной справочной информации из файла readme.txt;
* `-s`/`--samples` -- вывод примеров использования.
+
Возможно также использование `--abbr` перед терминами, чтобы получить строки, подходящие для вставки в текст в качестве всплывающих подсказок, в формате:
+
[html]
----
<abbr title="full_term">short_term</abbr>
----
+
[start=5]
. Повторить ввод терминов при необходимости.
. Для завершения работы ввести один из символов:
+
* `__exit__`/`__quit__`
* `exit`/`quit`
* `!exit`/`!quit`
* `!e`/`!q`

CAUTION: На Рабочем столе (Desktop) создается, а затем при успешном завершении работы удаляется директория
`_terms_logs`.
Она используется для хранения журнала `terms_debug`.
