[[table-cols]]
= Руководство для table-cols
:imagesdir: images
:stylesdir: ../css
:stylesheet: default.css
:pdf-themesdir: themes
:pdf-theme: base-theme.yml
:script-name: table-cols
:asciidoctorconfigdir: ..

== Описание

Скрипт задает ширины столбцов в таблицах файлов AsciiDoc, если не задана опция `[cols=""]`.

== Для чего нужно?

Если для таблицы не указаны параметры столбцов, то при обработке процессором столбцы имеют одинаковые ширины.
Немного существует таких таблиц, для которых такая конфигурация наиболее актуальная и подходящая.

include::partials/run.adoc[]

=== Опции скрипта

[source,console,subs="attributes+"]
----
Использование:
{name} {script-name}
-f/--file FILE ... FILE | -d/--dir DIR | -s/--max-symbols WIDTH | -c/--min-column WIDTH |
-r/--recursive | -o/--add-options | -k/--keep-logs | --h/--help

  Команда для задания ширины столбцам таблиц

Опции:
  -f, --file FILE ... FILE               Файл для обработки. Может использоваться несколько раз
  -d, --dir DIR                          Директория для обработки
  -s, --max-symbols WIDTH                Максимальная ширина столбца в символах.
                                         По умолчанию: 68.
                                         Примечание. Должно быть целым положительным числом
  -c, --min-column WIDTH                 Минимальная ширина столбца в символах.
                                         По умолчанию: 4.
                                         Примечание. Должно быть целым положительным числом
  -o, --add-options / -O, --no-options   Флаг добавления опций таблицы.
                                         По умолчанию: True, добавляются:
                                         * options="header";
                                         * width="100%"
  {recursive}
                                         {recursive-note}
  {keep-logs}
                                         {keep-logs-cont}
                                         {keep-logs-default}
  {help}
                                         {help-cont}
-------------------------------------------------------------------------------------------------
----

=== Примеры

include::partials/table-cols.adoc[]

NOTE: Путь может быть как абсолютным, так и относительным.

== Принцип работы Analyzer

. Для каждой ячейки вычислить минимальную ширину, необходимую для размещения текста без вынужденных разрывов.
+
NOTE: Ширина не может быть меньше, чем `--min-column`.
+
. Для каждого столбца вычислить минимальную ширину, равную максимуму из минимальных ширин ячеек.
. Для каждой ячейки вычислить рекомендуемую ширину, необходимую для размещения текста в одну строку.
. Для каждого столбца вычислить рекомендуемую ширину, равную максимуму из рекомендуемых ширин ячеек.
. Для таблицы вычислить минимальную ширину, равную сумме минимальных ширин столбцов.
. Проверить, что минимальная ширина не превышает `--max-symbols`.
. Столбцам, в которых нет ячеек с табуляцией, задать ширину, равную их рекомендуемой.
+
NOTE: В таких столбцах минимальная ширина равна рекомендуемой.
+
. Остальным столбцам задать ширину, равную их минимальной.
+
NOTE: Минимальная и рекомендуемая ширина столбца не может быть меньше, чем `--min-column`.
+
. Если сумма заданных ширин меньше максимально допустимой, то определить доступный остаток.
. Рассчитать доли для столбцов, пропорциональные рекомендуемым ширинам за вычетом уже заданных величин.
. Добавить к каждой ширине столбцов долю от доступного остатка.