[[check-russian]]
= Руководство для check-russian
:imagesdir: images
:stylesdir: ../css
:stylesheet: default.css
:toc-title: Содержание
:pdf-themesdir: themes
:pdf-theme: base-theme.yml
:asciidoctorconfigdir: ../

== Описание

Скрипт проверяет наличие кириллических символов в файлах.

В результате отображается информация, найдены ли не латинские символы:

[,log]
----
В файле <path to file> <найдены/не найдены> кириллические буквы [в строках: <line no>, ..., <line no>]
----

* `path to file` -- путь до файла;
* `line no` -- номер строки в файле, где найдены кириллические символы.

Поскольку в выводе возможно много строк, то для удобства ориентирования в нем используется интуитивная цветовая индикация.

CAUTION: Скрипт не показывает непереведенные слова или подмены схожих букв, это остается делом пользователя, а указывает лишь на файлы, строки и символы.

== Для чего нужно?

При переводе вручную можно вполне себе забыть или не заметить какие-то фразы/слова/предложения, оставшиеся на русском языке.

include::partials/run.adoc[]

=== Опции скрипта

[source,console,subs="attributes+"]
----
Использование:
{name} {script-name}
-d/--dir DIR | -f/--file FILE ... FILE | --verbose | --recursive | --keep-logs | --h/--help

  Команда для проверки наличия непереведенных слов

Опции:
  -d, --dir DIR                          Директория для обработки
  -f, --file FILE ... FILE               Файл для обработки. Может использоваться несколько раз
  --verbose / --no-verbose               Флаг подробного вывода.
                                         По умолчанию: False, выводятся только ошибки
  --recursive / --no-recursive           Флаг рекурсивного поиска файлов.
                                         По умолчанию: True, вложенные файлы учитываются
  --keep-logs                            Флаг сохранения директории с лог-файлом по завершении
                                         работы в штатном режиме.
                                         По умолчанию: False, лог-файл и директория удаляются
  -h, --help                             Вывести справочную информацию на экран и завершить
                                         работу
------------------------------------------------------------------------------------------------
----

NOTE: При указании директории в ней выбираются файлы, в которых присутствует постфикс `.en`.

NOTE: Путь может быть как абсолютным, так и относительным.

=== Пример

include::partials/check-russian.adoc[]
