[[auto-update]]
= Механизм автообновления
:imagesdir: images
:stylesdir: ../css
:stylesheet: default.css
:toc-title: Содержание
:pdf-themesdir: themes
:pdf-theme: base-theme.yml
:asciidoctorconfigdir: ../

== Описание

В версии 2.1.0 добавлено автоматическое обновление исполняемого файла.

Основной алгоритм работы:

. Проверяется наличие переменной окружения `_TW_UTILITIES_UPDATE`.
+
* Если переменная окружения не найдена, то:
+
[arabic]
. Добавляется переменная окружения `_TW_UTILITIES_UPDATE`.
. Присваивается значение 1.
. Выполняется переход к загрузке файла.
+
* Если переменная окружения найдена, то:
+
. Задается текущая версия на основе `pyproject.toml::project::version`.
. Отправляется запрос на `gitlab.com/tech_writers_protei/utilities/` на получение файла `pyproject.toml`.
+
* Если запрос неудачен, то далее скрипт выполняет основную команду.
* Если запрос удачен, то:
+
. Из загруженного файла считывается версия, `version`.
. Сравниваются значения.
+
* Если значения равны, то далее скрипт выполняет основную команду.
* Если значения не равны, то:
+
. Загружается новый исполняемый файл из репозитория.
. Новый файл заменяет старый.
. Далее скрипт выполняет основную команду.

== Переменная _TW_UTILITIES_UPDATE

Возможные значения:

* Активация:
+
** 1
** "1"
** yes
** on
+
* Деактивация:
+
** 0
** "0"
** no
** off

== Как отключить автоматическое обновление?

Чтобы отключить механизм, можно использовать один из методов:

. Задать деактивацию `_TW_UTILITIES_UPDATE`:
+
* Windows:
+
[source,powershell]
----
[Environment]::SetEnvironmentVariable("_TW_UTILITIES_UPDATE", "0", "User");
RefreshEnv.cmd;
----
+
* ++*++nix:
+
[source,shell]
----
$ echo "_TW_UTILITIES_UPDATE=0" >> ~/.bashrc;
$ source ~/.bashrc
----
+
. Использовать опцию -U/--no-update в команде:
* Windows:
+
[source,powershell]
----
.\tw_utilities.exe  --no-update <command> <options>
----
* ++*++nix:
+
[source,shell]
----
$ tw_utilities --no-update <command> <options>
----
+
. Разорвать соединение с Интернетом, чтобы запросы к репозиторию git были неуспешными.

[CAUTION]
Для самых наблюдательных: если задать _TW_UTILITIES_UPDATE = -1, то напоминание не будет отображаться в консоли, а скрипт не будет пытаться обновиться.
Может быть полезно, если запускается много скриптов подряд, поскольку в этом случае игнорируется вся проверка и сравнение версий, а также загрузка файла.
Это ускорит и упростит запуск, а также вывод консоли будет почище.
